### ISSUE TITLE
Error when installing packages

### ISSUE THREAD

**Issue by evasterviga** [s1la/python_project_SS#1]
Hello,

The code looks super nice. However I did run in to an issue that I would like you to fix. If you have any questions or get stuck don't hesitate to contact me and we can solve it together!

When I run `pip install -r requirements_python_project_SS.txt` I get the following errors:
```
ERROR: Could not find a version that satisfies the requirement conda-content-trust==0.1.3 (from versions: none)
ERROR: No matching distribution found for conda-content-trust==0.1.3

ERROR: Could not find a version that satisfies the requirement conda-libmamba-solver==23.5.0 (from versions: none)
ERROR: No matching distribution found for conda-libmamba-solver==23.5.0
```

Are these packages necessary to run your code? Also, you can of course do it as you like, but did you know that you might not need both a `requerements.txt` and `conda.yml` file. For example, pip dependencies can be included in your conda.yml file kind of like this:
```
name: base
channels:
  - defaults
dependencies:
  - python=3.11
  - conda==23.5.2
  - setuptools
  - pip
  - pip:
     - Bottleneck
     - brotlipy
```
and so on. I also see that you install pip in both `conda.yml` and `requirements.txt`. Perhaps some packages are not even necessary to include in these files. That could be something to investigate. 

Anyways, as long as I can install all the packages without any errors it's fine. Then I will move on and try out running the script.

PS. in the `conda.yml` it says that the name is "base". That is usually the name of the base environment that you use when you are not in special project related environments. That could get confusing. :)

**Comment by s1la** [comment]
Hi! I changed the name in the .yml file, and added the pip dependencies in there. I removed the packages that were installed in the original conda.yml and the pip requirements. I hope it works now!

**Comment by evasterviga** [comment]
It looks good! I could run the script and I will approve the project.

Some notes for the future:

I got this error when creating the environment:

```
ResolvePackageNotFound:
  - console_shortcut_miniconda
  - powershell_shortcut_miniconda
```
However, I couldn't find out what they were for very quickly so I just tried removing them from the .ylm file and it worked. :) Do you know what they do? It's up to you if you want to change it for future usage of the repo.. 


I was going to comment about the prefix in the .yml file but I found out that.it's okay to keep [here](https://stackoverflow.com/questions/41274007/anaconda-export-environment-file). Cool.


Lastly, I think you have a very nice repo. The code is easy to follow and well structured which is very helpful. The README was also informative which is so nice. I hope the project helps you in your work! I saw that there were some functions within functions in the code. That's not maybe the conventional way to write it but it works, so all is well. (And you shouldn't write too much like others do but stick to what works for you!)

**Comment by s1la** [comment]
Thank you so much for the feedback! I will look into the .yml some more - it was my first time creating one :) and thank you for the nice course!
